---
title: Results
format:
  html:
    embed-resources: true
    code-fold: true
    code-summary: "Show the code"
toc: true
theme:
  light: flatly
  dark: darkly
date: last-modified
editor_options: 
  chunk_output_type: console
execute: 
  echo: true
  fig-dpi: 400
  error: true
  cache: false
  warning: false
---

```{r}
#| label: setup
#| include: false

source("utils.R")
```

```{r}
#| label: import

esg_sparse <- pin_read(board, "esg_sparse")
covariates <- pin_read(board, "covariates")

raw_text <- pin_read(board, "raw_text") |> 
  mutate(raw_text = map(raw_text, 1)) %>% 
  rename(symbol=company,
         time=year) %>% 
  mutate(time=as.numeric(time),
        has_report="Available CSR report")
```


```{r}
table1<-pin_read(board, "esg_score_df_eikon") %>% 
  left_join(raw_text,by=c("symbol","time"))%>% 
  select(-raw_text) %>% 
  group_by(time,has_report) %>% 
  summarise(n=n(),
            q25 = quantile(esg_score, probs =0.25),
            median=median(esg_score),
            q75 = quantile(esg_score, probs =0.75))


table2<-pin_read(board, "esg_score_df_eikon") %>% 
  left_join(raw_text,by=c("symbol","time"))%>% 
  select(-raw_text) %>% 
  group_by(symbol) %>% 
  mutate(min_year=min(time)) %>% 
  filter(time==2020) %>% 
  group_by(min_year) %>% 
  summarise(n=n(),
            median=median(esg_score),
            avg=mean(esg_score),
            std_dev=sd(esg_score,na.rm=TRUE))
  
  

table_proba<-table1 %>% 
  pivot_longer(-c(1,2,3))


ggplot(table_proba, 
       aes(x = time, y = value, colour=has_report, group = has_report)) +  
  geom_line() + geom_point()+
  facet_grid(~factor(name, levels=c('q25','median','q75')))+
  scale_color_manual(values=c('#063970', '#A69943'))+
  geom_line(size=1.5)



```

```{r}
pin_read(board, "k_result_stm-improve_total_score") |> 
  select(
    K,
    `Lower bound`,
    Residuals,
    `Semantic coherence`,
    `Held-out likelihood`
  ) |> 
  pivot_longer(-K, names_to = "metric") |> 
  ggplot(aes(K, value, color = metric)) +
  geom_line(size = 1, show.legend = FALSE) +
  geom_point(show.legend = FALSE) +
  facet_wrap(~ metric, scales = "free_y") +
  labs(x = "K (number of topics)",
       y = NULL,
       title = "Model diagnostics by number of topics",
       subtitle = "These diagnostics indicate that a good number of topic")

```

### Beta for terms

```{r}
#| results: asis
#| echo: false

file_names <- pin_list(board)|> 
  keep(str_detect, "stm-time_\\d{1,2}") |> 
  str_remove_all("\\D") |> 
  as.numeric() |> 
  sort()

cat('::: {.panel-tabset group="Topic number"}\n\n')

file_names |> 
  walk(.f = function(k) {
    cat(str_c("#### ", k, "\n\n"))
    
    str_c("stm-time_", k) |> 
      pin_read(board = board) |> 
      pluck(1) |> 
      broom::tidy() |> 
      group_by(topic) |> 
      slice_max(beta, n = 10) |> 
      summarise(terms = str_flatten(term, ", ")) |> 
      gt::gt() |> 
      print()
    
    cat("\n")
  })

cat(":::")
```