---
title: "manuscript"
format: docx
editor: visual
---

```{r}
#| label: setup
#| include: false

source("utils.R")
```

```{r}
#| label: import

esg_sparse <- pin_read(board, "esg_sparse")
covariates <- pin_read(board, "covariates")

raw_text <- pin_read(board, "raw_text") |> 
  mutate(raw_text = map(raw_text, 1))

sp500 <- tq_index("SP500") %>% 
  select(1,2,5,6)

pin_list(board) |> 
  keep(str_detect, "stm-improve_total_score-sector_") |> 
  map(pin_read, board = board) |> 
  map(1)
```


```{r}
esg_score %>% 
  left_join(sp500) %>% 
  filter(year<2019) %>% 
  drop_na() %>% 
  ggplot(aes(x=year, y=score, fill=sector)) + 
  geom_boxplot() +
  facet_wrap(~sector)
```

```{r}
pin_read(board, "k_result_stm-improve_total_score-sector")  %>%
  transmute(
    K,
    `Lower bound` = lbound,
    Residuals = map_dbl(residual, "dispersion"),
    `Semantic coherence` = map_dbl(semantic_coherence, mean),
    `Held-out likelihood` = map_dbl(eval_heldout, "expected.heldout")
  ) %>%
  gather(Metric, Value, -K) %>%
  ggplot(aes(K, Value, color = Metric)) +
  geom_line(size = 1.5, alpha = 0.7, show.legend = FALSE) +
  facet_wrap(~Metric, scales = "free_y") +
  labs(x = "K (number of topics)",
       y = NULL,
       title = "Model diagnostics by number of topics",
       subtitle = "These diagnostics indicate that a good number of topic")

```

